In [7]:
import torch
import numpy as np

In [3]:
t = torch.Tensor([1,2,3])

In [4]:
t

tensor([1., 2., 3.])

In [5]:
t.shape

torch.Size([3])

In [8]:
t1 = torch.Tensor([1,2,3])
t2 = torch.tensor([1,2,3])
t3 = torch.as_tensor([1,2,3])
t4 = torch.from_numpy(np.array([1,2,3]))

In [15]:
img = torch.tensor([
    [
        [[1,1,1,1],
        [1,1,1,1],
        [1,1,1,1],
        [1,1,1,1]],
        
        [[2,2,2,2],
        [2,2,2,2],
        [2,2,2,2],
        [2,2,2,2]],
        
        [[3,3,3,3],
        [3,3,3,3],
        [3,3,3,3],
        [3,3,3,3]]
    ]
], dtype=torch.float32)

In [16]:
img.shape

torch.Size([1, 3, 4, 4])

In [17]:
img.reshape(3, -1).shape

torch.Size([3, 16])

In [18]:
img

tensor([[[[1., 1., 1., 1.],
          [1., 1., 1., 1.],
          [1., 1., 1., 1.],
          [1., 1., 1., 1.]],

         [[2., 2., 2., 2.],
          [2., 2., 2., 2.],
          [2., 2., 2., 2.],
          [2., 2., 2., 2.]],

         [[3., 3., 3., 3.],
          [3., 3., 3., 3.],
          [3., 3., 3., 3.],
          [3., 3., 3., 3.]]]])

In [20]:
img.argmax(dim=0)

tensor([[[0, 0, 0, 0],
         [0, 0, 0, 0],
         [0, 0, 0, 0],
         [0, 0, 0, 0]],

        [[0, 0, 0, 0],
         [0, 0, 0, 0],
         [0, 0, 0, 0],
         [0, 0, 0, 0]],

        [[0, 0, 0, 0],
         [0, 0, 0, 0],
         [0, 0, 0, 0],
         [0, 0, 0, 0]]])

In [26]:
img.mean()==2, img.mean().item()==2

(tensor(True), True)