In [14]:
import torch

In [15]:
torch.__version__

'1.10.1'

In [9]:
!python --version

Python 3.9.7


In [10]:
!which python

/Users/rs/opt/anaconda3/envs/pytorch-e/bin/python


In [11]:
!/Users/rs/opt/anaconda3/envs/pytorch-e/bin/python

Python 3.9.7 (default, Sep 16 2021, 08:50:36) 
[Clang 10.0.0 ] :: Anaconda, Inc. on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> 
KeyboardInterrupt
>>> 
>>> 

In [ ]:
import pytorch

In [12]:
!conda list

# packages in environment at /Users/rs/opt/anaconda3/envs/pytorch-e:
#
# Name                    Version                   Build  Channel
appnope                   0.1.2           py39hecd8cb5_1001  
argon2-cffi               20.1.0           py39h9ed2024_1  
async_generator           1.10               pyhd3eb1b0_0  
attrs                     21.2.0             pyhd3eb1b0_0  
backcall                  0.2.0              pyhd3eb1b0_0  
blas                      1.0                         mkl  
bleach                    4.1.0              pyhd3eb1b0_0  
bzip2                     1.0.8                h1de35cc_0  
ca-certificates           2021.10.26           hecd8cb5_2  
certifi                   2021.10.8        py39hecd8cb5_2  
cffi                      1.14.6           py39h2125817_0  
debugpy                   1.5.1            py39he9d5cce_0  
decorator                 5.1.0              pyhd3eb1b0_0  
defusedxml                0.7.1              pyhd3eb1b0_0  
entrypoints         

In [13]:
!conda install pytorch torchvision torchaudio -c pytorch -y


Solving environment: done

# All requested packages already installed.



In [17]:
my_tensor = torch.tensor([[1,2,3], [1,3, 4]], dtype=torch.float32)

In [18]:
my_tensor

tensor([[1., 2., 3.],
        [1., 3., 4.]])

In [19]:
my_tensor.dtype

torch.float32

In [20]:
my_tensor.shape

torch.Size([2, 3])

In [21]:
my_tensor.requires_grad

False

In [22]:
new_tensor = torch.rand((4,5))

In [23]:
new_tensor

tensor([[0.7910, 0.0577, 0.0359, 0.2111, 0.0883],
        [0.5366, 0.3496, 0.2727, 0.3012, 0.4194],
        [0.9819, 0.5021, 0.0336, 0.2636, 0.0255],
        [0.0923, 0.6445, 0.3208, 0.0397, 0.9447]])

In [24]:
one_tensor = torch.ones((2,2))

In [25]:
one_tensor

tensor([[1., 1.],
        [1., 1.]])

In [26]:
zero_tensor = torch.zeros((5,5))

In [27]:
zero_tensor

tensor([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]])

In [28]:
diag_tensor = torch.eye(5,5)

In [29]:
diag_tensor

tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])

In [30]:
range_tensor = torch.arange(0,5,2)

In [31]:
range_tensor

tensor([0, 2, 4])

In [33]:
torch.linspace(0.1,1,10)

tensor([0.1000, 0.2000, 0.3000, 0.4000, 0.5000, 0.6000, 0.7000, 0.8000, 0.9000,
        1.0000])

In [34]:
torch.empty(size=(1,5)).normal_(mean=0, std=1)

tensor([[ 0.8624,  0.1913,  0.5017,  0.4169, -1.2919]])

In [36]:
torch.empty(size=(1,5)).uniform_(0, 1)

tensor([[0.2536, 0.0196, 0.7609, 0.7581, 0.6547]])

In [39]:
torch.zeros_like(range_tensor)

tensor([0, 0, 0])

In [40]:
torch.ones_like(range_tensor)

tensor([1, 1, 1])

In [41]:
torch.diag(torch.ones(5))

tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])

In [42]:
## converting tensor to other types

In [43]:
torch.ones((3,3)).bool()

tensor([[True, True, True],
        [True, True, True],
        [True, True, True]])

In [45]:
torch.ones((3,3)).short()

tensor([[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]], dtype=torch.int16)

In [46]:
torch.ones((3,3)).long()

tensor([[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]])

In [47]:
torch.ones((3,3)).half()

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float16)

In [48]:
torch.ones((3,3)).float() # float32

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])

In [49]:
torch.ones((3,3)).double()

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)

In [50]:
import numpy as np

In [51]:
np_arr = np.ones((6,7))
t_arr = torch.from_numpy(np_arr)

In [52]:
t_arr

tensor([[1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1.]], dtype=torch.float64)

In [53]:
t_arr.numpy()

array([[1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.]])

In [54]:
t1 = torch.tensor([1,2,3])
t2 = torch.tensor([3,4,5])
t1+t2

tensor([4, 6, 8])

In [55]:
t3 = torch.tensor([3])
t1+t3

tensor([4, 5, 6])

In [56]:
t1-t3

tensor([-2, -1,  0])

In [57]:
t3-t1

tensor([2, 1, 0])

In [58]:
torch.add(t1, t2)

tensor([4, 6, 8])

In [59]:
torch.subtract(t1, t2)

tensor([-2, -2, -2])

In [60]:
t1/t2

tensor([0.3333, 0.5000, 0.6000])

In [61]:
torch.true_divide(t1, t2)

tensor([0.3333, 0.5000, 0.6000])

In [62]:
torch.divide(t1, t2)

tensor([0.3333, 0.5000, 0.6000])

In [63]:
# inplace operations
t1.add_(t2)

tensor([4, 6, 8])

In [64]:
t1

tensor([4, 6, 8])

In [65]:
t2

tensor([3, 4, 5])

In [66]:
t1.pow(2)

tensor([16, 36, 64])

In [67]:
t1 > t2

tensor([True, True, True])

In [69]:
t3 = torch.rand((2,3))
t4 = torch.rand((3,7))
torch.mm(t3, t4)

tensor([[0.2740, 0.2760, 0.3230, 0.4496, 0.2436, 0.4736, 0.4370],
        [0.1392, 0.0264, 0.1197, 0.0952, 0.2766, 0.0714, 0.1428]])

In [70]:
t3.mm(t4)

tensor([[0.2740, 0.2760, 0.3230, 0.4496, 0.2436, 0.4736, 0.4370],
        [0.1392, 0.0264, 0.1197, 0.0952, 0.2766, 0.0714, 0.1428]])

In [71]:
t3.matmul(t4)

tensor([[0.2740, 0.2760, 0.3230, 0.4496, 0.2436, 0.4736, 0.4370],
        [0.1392, 0.0264, 0.1197, 0.0952, 0.2766, 0.0714, 0.1428]])

In [75]:
t3.matrix_power(2)

RuntimeError: A must be batches of square matrices, but they are 3 by 2 matrices

In [76]:
t5 = torch.rand((3,3))
t5.matrix_power(3)

tensor([[0.7314, 0.4491, 0.3994],
        [0.8563, 0.5361, 0.5793],
        [0.9351, 0.6052, 0.6331]])

In [78]:
t5.matrix_exp()

tensor([[2.1809, 0.6989, 0.2538],
        [0.9782, 1.5162, 1.0194],
        [0.9928, 0.7901, 1.9861]])

In [79]:
t5

tensor([[0.6819, 0.4183, 0.0135],
        [0.4520, 0.1483, 0.6544],
        [0.4201, 0.4158, 0.5496]])

In [81]:
t3.shape, t4.shape

(torch.Size([2, 3]), torch.Size([3, 7]))

In [82]:
t5.matrix_power(2)

tensor([[0.6598, 0.3529, 0.2903],
        [0.6502, 0.4832, 0.4628],
        [0.7053, 0.4659, 0.5798]])

In [83]:
t5*t5

tensor([[4.6503e-01, 1.7500e-01, 1.8094e-04],
        [2.0434e-01, 2.2004e-02, 4.2829e-01],
        [1.7646e-01, 1.7285e-01, 3.0207e-01]])

In [84]:
t5.mm(t5)

tensor([[0.6598, 0.3529, 0.2903],
        [0.6502, 0.4832, 0.4628],
        [0.7053, 0.4659, 0.5798]])

In [87]:
torch.dot(t5.ravel(), t5.ravel())

tensor(1.9462)

In [88]:
t5

tensor([[0.6819, 0.4183, 0.0135],
        [0.4520, 0.1483, 0.6544],
        [0.4201, 0.4158, 0.5496]])

In [89]:
t5.ravel()

tensor([0.6819, 0.4183, 0.0135, 0.4520, 0.1483, 0.6544, 0.4201, 0.4158, 0.5496])

In [90]:
t6 = torch.rand((1,2,3))

In [91]:
t6

tensor([[[0.9767, 0.9921, 0.1335],
         [0.2165, 0.0372, 0.9321]]])

In [92]:
t6.ravel()

tensor([0.9767, 0.9921, 0.1335, 0.2165, 0.0372, 0.9321])

In [95]:
batch = 2
t1 = torch.rand((batch, 3, 4))
t2 = torch.rand((batch, 4, 2))
torch.bmm(t1, t2)

tensor([[[0.8422, 1.2939],
         [0.5176, 1.1730],
         [0.7277, 1.0119]],

        [[1.8849, 1.8306],
         [2.3173, 2.2487],
         [1.4477, 1.5821]]])

In [98]:
torch.sum(t1), torch.sum(t1, dim=0), torch.sum(t1, dim=1), torch.sum(t1, dim=2)

(tensor(12.9537),
 tensor([[0.8585, 1.2835, 0.6635, 1.6947],
         [0.7537, 1.6699, 0.7794, 1.7013],
         [1.1576, 0.3525, 1.2771, 0.7621]]),
 tensor([[0.9005, 1.5218, 0.6944, 2.0943],
         [1.8692, 1.7841, 2.0256, 2.0637]]),
 tensor([[2.0070, 1.7379, 1.4662],
         [2.4931, 3.1665, 2.0831]]))

In [99]:
torch.max(t1), torch.max(t1, dim=0), torch.max(t1, dim=1), torch.max(t1, dim=2)

(tensor(0.9730),
 torch.return_types.max(
 values=tensor([[0.5437, 0.6770, 0.6049, 0.9669],
         [0.5814, 0.8848, 0.7667, 0.9335],
         [0.9730, 0.2928, 0.6540, 0.5988]]),
 indices=tensor([[0, 0, 1, 1],
         [1, 1, 1, 1],
         [1, 1, 1, 0]])),
 torch.return_types.max(
 values=tensor([[0.5437, 0.7851, 0.6231, 0.7678],
         [0.9730, 0.8848, 0.7667, 0.9669]]),
 indices=tensor([[0, 1, 2, 1],
         [2, 1, 1, 0]])),
 torch.return_types.max(
 values=tensor([[0.7277, 0.7851, 0.6231],
         [0.9669, 0.9335, 0.9730]]),
 indices=tensor([[3, 1, 2],
         [3, 3, 0]])))

In [100]:
torch.min(t1), torch.min(t1, dim=0), torch.min(t1, dim=1), torch.min(t1, dim=2)

(tensor(0.0127),
 torch.return_types.min(
 values=tensor([[0.3148, 0.6065, 0.0586, 0.7277],
         [0.1723, 0.7851, 0.0127, 0.7678],
         [0.1846, 0.0597, 0.6231, 0.1632]]),
 indices=tensor([[1, 1, 0, 0],
         [0, 0, 0, 0],
         [0, 0, 0, 1]])),
 torch.return_types.min(
 values=tensor([[0.1723, 0.0597, 0.0127, 0.5988],
         [0.3148, 0.2928, 0.6049, 0.1632]]),
 indices=tensor([[1, 2, 1, 2],
         [0, 2, 0, 2]])),
 torch.return_types.min(
 values=tensor([[0.0586, 0.0127, 0.0597],
         [0.3148, 0.5814, 0.1632]]),
 indices=tensor([[2, 2, 1],
         [0, 0, 3]])))

In [101]:
torch.argmax(t1), torch.argmax(t1, dim=0), torch.argmax(t1, dim=1), torch.argmax(t1, dim=2)

(tensor(20),
 tensor([[0, 0, 1, 1],
         [1, 1, 1, 1],
         [1, 1, 1, 0]]),
 tensor([[0, 1, 2, 1],
         [2, 1, 1, 0]]),
 tensor([[3, 1, 2],
         [3, 3, 0]]))

In [102]:
t1

tensor([[[0.5437, 0.6770, 0.0586, 0.7277],
         [0.1723, 0.7851, 0.0127, 0.7678],
         [0.1846, 0.0597, 0.6231, 0.5988]],

        [[0.3148, 0.6065, 0.6049, 0.9669],
         [0.5814, 0.8848, 0.7667, 0.9335],
         [0.9730, 0.2928, 0.6540, 0.1632]]])

In [103]:
torch.mean(t1), torch.mean(t1, dim=0), torch.mean(t1, dim=1), torch.mean(t1, dim=2)

(tensor(0.5397),
 tensor([[0.4292, 0.6417, 0.3317, 0.8473],
         [0.3768, 0.8350, 0.3897, 0.8507],
         [0.5788, 0.1762, 0.6385, 0.3810]]),
 tensor([[0.3002, 0.5073, 0.2315, 0.6981],
         [0.6231, 0.5947, 0.6752, 0.6879]]),
 tensor([[0.5018, 0.4345, 0.3665],
         [0.6233, 0.7916, 0.5208]]))

In [105]:
torch.eq(t1, t1)

tensor([[[True, True, True, True],
         [True, True, True, True],
         [True, True, True, True]],

        [[True, True, True, True],
         [True, True, True, True],
         [True, True, True, True]]])

In [106]:
torch.sort(t1, dim=0, descending=False)

torch.return_types.sort(
values=tensor([[[0.3148, 0.6065, 0.0586, 0.7277],
         [0.1723, 0.7851, 0.0127, 0.7678],
         [0.1846, 0.0597, 0.6231, 0.1632]],

        [[0.5437, 0.6770, 0.6049, 0.9669],
         [0.5814, 0.8848, 0.7667, 0.9335],
         [0.9730, 0.2928, 0.6540, 0.5988]]]),
indices=tensor([[[1, 1, 0, 0],
         [0, 0, 0, 0],
         [0, 0, 0, 1]],

        [[0, 0, 1, 1],
         [1, 1, 1, 1],
         [1, 1, 1, 0]]]))

In [107]:
t1

tensor([[[0.5437, 0.6770, 0.0586, 0.7277],
         [0.1723, 0.7851, 0.0127, 0.7678],
         [0.1846, 0.0597, 0.6231, 0.5988]],

        [[0.3148, 0.6065, 0.6049, 0.9669],
         [0.5814, 0.8848, 0.7667, 0.9335],
         [0.9730, 0.2928, 0.6540, 0.1632]]])

In [108]:
torch.sort(t1, dim=1, descending=False)

torch.return_types.sort(
values=tensor([[[0.1723, 0.0597, 0.0127, 0.5988],
         [0.1846, 0.6770, 0.0586, 0.7277],
         [0.5437, 0.7851, 0.6231, 0.7678]],

        [[0.3148, 0.2928, 0.6049, 0.1632],
         [0.5814, 0.6065, 0.6540, 0.9335],
         [0.9730, 0.8848, 0.7667, 0.9669]]]),
indices=tensor([[[1, 2, 1, 2],
         [2, 0, 0, 0],
         [0, 1, 2, 1]],

        [[0, 2, 0, 2],
         [1, 0, 2, 1],
         [2, 1, 1, 0]]]))

In [109]:
t1

tensor([[[0.5437, 0.6770, 0.0586, 0.7277],
         [0.1723, 0.7851, 0.0127, 0.7678],
         [0.1846, 0.0597, 0.6231, 0.5988]],

        [[0.3148, 0.6065, 0.6049, 0.9669],
         [0.5814, 0.8848, 0.7667, 0.9335],
         [0.9730, 0.2928, 0.6540, 0.1632]]])

In [110]:
torch.sort(t1, dim=2, descending=False)

torch.return_types.sort(
values=tensor([[[0.0586, 0.5437, 0.6770, 0.7277],
         [0.0127, 0.1723, 0.7678, 0.7851],
         [0.0597, 0.1846, 0.5988, 0.6231]],

        [[0.3148, 0.6049, 0.6065, 0.9669],
         [0.5814, 0.7667, 0.8848, 0.9335],
         [0.1632, 0.2928, 0.6540, 0.9730]]]),
indices=tensor([[[2, 0, 1, 3],
         [2, 0, 3, 1],
         [1, 0, 3, 2]],

        [[0, 2, 1, 3],
         [0, 2, 1, 3],
         [3, 1, 2, 0]]]))

In [111]:
t1_sort = torch.sort(t1, dim=2, descending=False)

In [112]:
t1_sort.values

tensor([[[0.0586, 0.5437, 0.6770, 0.7277],
         [0.0127, 0.1723, 0.7678, 0.7851],
         [0.0597, 0.1846, 0.5988, 0.6231]],

        [[0.3148, 0.6049, 0.6065, 0.9669],
         [0.5814, 0.7667, 0.8848, 0.9335],
         [0.1632, 0.2928, 0.6540, 0.9730]]])

In [114]:
t1_sort.indices

tensor([[[2, 0, 1, 3],
         [2, 0, 3, 1],
         [1, 0, 3, 2]],

        [[0, 2, 1, 3],
         [0, 2, 1, 3],
         [3, 1, 2, 0]]])

In [116]:
torch.clamp(t1, min=1)

tensor([[[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]])

In [117]:
torch.clamp(t1, min=1).eq(1)

tensor([[[True, True, True, True],
         [True, True, True, True],
         [True, True, True, True]],

        [[True, True, True, True],
         [True, True, True, True],
         [True, True, True, True]]])

In [118]:
torch.clamp(t1, min=1).eq(1).any()

tensor(True)

In [119]:
torch.clamp(t1, min=1).eq(1).all()

tensor(True)

In [120]:
t1

tensor([[[0.5437, 0.6770, 0.0586, 0.7277],
         [0.1723, 0.7851, 0.0127, 0.7678],
         [0.1846, 0.0597, 0.6231, 0.5988]],

        [[0.3148, 0.6065, 0.6049, 0.9669],
         [0.5814, 0.8848, 0.7667, 0.9335],
         [0.9730, 0.2928, 0.6540, 0.1632]]])

In [123]:
t1[0], t1[0][0], t1[0][0][0]

(tensor([[0.5437, 0.6770, 0.0586, 0.7277],
         [0.1723, 0.7851, 0.0127, 0.7678],
         [0.1846, 0.0597, 0.6231, 0.5988]]),
 tensor([0.5437, 0.6770, 0.0586, 0.7277]),
 tensor(0.5437))

In [125]:
t1[:,0]

tensor([[0.5437, 0.6770, 0.0586, 0.7277],
        [0.3148, 0.6065, 0.6049, 0.9669]])

In [129]:
t1[:,0, 1]

tensor([0.6770, 0.6065])

In [138]:
t1[torch.tensor([1,1]), torch.tensor([1,1]),torch.tensor([1,1])]

tensor([0.8848, 0.8848])

In [139]:
t1.remainder(2)

tensor([[[0.5437, 0.6770, 0.0586, 0.7277],
         [0.1723, 0.7851, 0.0127, 0.7678],
         [0.1846, 0.0597, 0.6231, 0.5988]],

        [[0.3148, 0.6065, 0.6049, 0.9669],
         [0.5814, 0.8848, 0.7667, 0.9335],
         [0.9730, 0.2928, 0.6540, 0.1632]]])

In [142]:
torch.where(t1 > 0)

(tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]),
 tensor([0, 0, 0, 0, 1, 1, 1, 1, 2, 2, 2, 2, 0, 0, 0, 0, 1, 1, 1, 1, 2, 2, 2, 2]),
 tensor([0, 1, 2, 3, 0, 1, 2, 3, 0, 1, 2, 3, 0, 1, 2, 3, 0, 1, 2, 3, 0, 1, 2, 3]))

In [144]:
torch.where(t1 > 0, t1, t1+4)

tensor([[[0.5437, 0.6770, 0.0586, 0.7277],
         [0.1723, 0.7851, 0.0127, 0.7678],
         [0.1846, 0.0597, 0.6231, 0.5988]],

        [[0.3148, 0.6065, 0.6049, 0.9669],
         [0.5814, 0.8848, 0.7667, 0.9335],
         [0.9730, 0.2928, 0.6540, 0.1632]]])

In [147]:
t1.ndimension(), t1.ndim

(3, 3)

In [148]:
t1.shape

torch.Size([2, 3, 4])

In [149]:
t1.numel()

24

In [150]:
t1.view(3,2,4)

tensor([[[0.5437, 0.6770, 0.0586, 0.7277],
         [0.1723, 0.7851, 0.0127, 0.7678]],

        [[0.1846, 0.0597, 0.6231, 0.5988],
         [0.3148, 0.6065, 0.6049, 0.9669]],

        [[0.5814, 0.8848, 0.7667, 0.9335],
         [0.9730, 0.2928, 0.6540, 0.1632]]])

In [151]:
t1.reshape(3,2,4)

tensor([[[0.5437, 0.6770, 0.0586, 0.7277],
         [0.1723, 0.7851, 0.0127, 0.7678]],

        [[0.1846, 0.0597, 0.6231, 0.5988],
         [0.3148, 0.6065, 0.6049, 0.9669]],

        [[0.5814, 0.8848, 0.7667, 0.9335],
         [0.9730, 0.2928, 0.6540, 0.1632]]])

In [153]:
torch.cat((t1, t1), dim=1)

tensor([[[0.5437, 0.6770, 0.0586, 0.7277],
         [0.1723, 0.7851, 0.0127, 0.7678],
         [0.1846, 0.0597, 0.6231, 0.5988],
         [0.5437, 0.6770, 0.0586, 0.7277],
         [0.1723, 0.7851, 0.0127, 0.7678],
         [0.1846, 0.0597, 0.6231, 0.5988]],

        [[0.3148, 0.6065, 0.6049, 0.9669],
         [0.5814, 0.8848, 0.7667, 0.9335],
         [0.9730, 0.2928, 0.6540, 0.1632],
         [0.3148, 0.6065, 0.6049, 0.9669],
         [0.5814, 0.8848, 0.7667, 0.9335],
         [0.9730, 0.2928, 0.6540, 0.1632]]])

In [154]:
torch.cat((t1, t1), dim=0)

tensor([[[0.5437, 0.6770, 0.0586, 0.7277],
         [0.1723, 0.7851, 0.0127, 0.7678],
         [0.1846, 0.0597, 0.6231, 0.5988]],

        [[0.3148, 0.6065, 0.6049, 0.9669],
         [0.5814, 0.8848, 0.7667, 0.9335],
         [0.9730, 0.2928, 0.6540, 0.1632]],

        [[0.5437, 0.6770, 0.0586, 0.7277],
         [0.1723, 0.7851, 0.0127, 0.7678],
         [0.1846, 0.0597, 0.6231, 0.5988]],

        [[0.3148, 0.6065, 0.6049, 0.9669],
         [0.5814, 0.8848, 0.7667, 0.9335],
         [0.9730, 0.2928, 0.6540, 0.1632]]])

In [155]:
t1.permute(0,2,1)

tensor([[[0.5437, 0.1723, 0.1846],
         [0.6770, 0.7851, 0.0597],
         [0.0586, 0.0127, 0.6231],
         [0.7277, 0.7678, 0.5988]],

        [[0.3148, 0.5814, 0.9730],
         [0.6065, 0.8848, 0.2928],
         [0.6049, 0.7667, 0.6540],
         [0.9669, 0.9335, 0.1632]]])

In [157]:
t1 = torch.rand((2,2,3))
t1

tensor([[[0.1967, 0.7062, 0.1559],
         [0.1173, 0.3932, 0.5924]],

        [[0.2978, 0.9453, 0.8965],
         [0.0850, 0.0933, 0.8546]]])

In [158]:
t1.unsqueeze(0)

tensor([[[[0.1967, 0.7062, 0.1559],
          [0.1173, 0.3932, 0.5924]],

         [[0.2978, 0.9453, 0.8965],
          [0.0850, 0.0933, 0.8546]]]])

In [159]:
t1.unsqueeze(1)

tensor([[[[0.1967, 0.7062, 0.1559],
          [0.1173, 0.3932, 0.5924]]],


        [[[0.2978, 0.9453, 0.8965],
          [0.0850, 0.0933, 0.8546]]]])

In [160]:
t1.squeeze()

tensor([[[0.1967, 0.7062, 0.1559],
         [0.1173, 0.3932, 0.5924]],

        [[0.2978, 0.9453, 0.8965],
         [0.0850, 0.0933, 0.8546]]])

In [161]:
torch.is_tensor(t1)

True

In [162]:
torch.is_storage(t1)

False

In [163]:
torch.is_storage(torch.arange(10))

False

In [164]:
torch.is_floating_point(t1)

True

In [166]:
torch.is_nonzero(t1.sum())

True

In [167]:
torch.get_default_dtype()

torch.float32

In [169]:
x = torch.rand(1000, 2, 2)
print(x) # prints the truncated tensor
torch.set_printoptions(threshold=10_000, sci_mode=False)
print(x) # prints the whole tensor

tensor([[[1.6408e-01, 8.7589e-01],
         [9.2553e-01, 9.6655e-01]],

        [[9.8930e-01, 3.8763e-02],
         [5.9412e-02, 7.1423e-01]],

        [[8.6693e-01, 4.7424e-02],
         [7.0637e-01, 7.4740e-01]],

        [[6.3983e-01, 2.7769e-01],
         [8.0023e-01, 2.9049e-01]],

        [[6.4796e-01, 1.7033e-01],
         [3.3017e-02, 6.5484e-01]],

        [[2.4363e-01, 5.2028e-01],
         [4.8769e-01, 2.8339e-01]],

        [[1.3965e-01, 8.8327e-02],
         [9.5184e-01, 2.8497e-01]],

        [[6.2869e-01, 4.5647e-01],
         [5.0378e-03, 6.2945e-01]],

        [[6.0422e-01, 1.6593e-02],
         [1.2553e-01, 9.5845e-01]],

        [[9.6874e-01, 2.9249e-01],
         [4.0955e-01, 2.8386e-01]],

        [[3.3862e-01, 4.5488e-01],
         [7.3341e-01, 8.2376e-01]],

        [[7.0607e-01, 6.4047e-01],
         [7.3747e-01, 1.2896e-01]],

        [[6.2157e-01, 3.1425e-01],
         [1.8699e-02, 2.6135e-01]],

        [[3.6392e-01, 2.0939e-01],
         [8.0032e-01, 1.0102e

In [171]:
a = np.array([1, 2, 3])
torch.as_tensor(a)

tensor([1, 2, 3])

In [172]:
torch.arange(1, 4), torch.arange(1, 2.5, 0.5)

(tensor([1, 2, 3]), tensor([1.0000, 1.5000, 2.0000]))

In [173]:
torch.range(1, 4), torch.range(1, 4, 0.5)

/var/folders/g5/gwd22q2n4hl4ljj5zn8bmq5r0000gn/T/ipykernel_89340/2647915040.py:1: UserWarning: torch.range is deprecated and will be removed in a future release because its behavior is inconsistent with Python's range builtin. Instead, use torch.arange, which produces values in [start, end).
  torch.range(1, 4), torch.range(1, 4, 0.5)


(tensor([1., 2., 3., 4.]),
 tensor([1.0000, 1.5000, 2.0000, 2.5000, 3.0000, 3.5000, 4.0000]))

In [174]:
torch.full((2, 3), 3.141592)

tensor([[3.1416, 3.1416, 3.1416],
        [3.1416, 3.1416, 3.1416]])